version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=8.2
    ports:
      - "80:80"
    environment:
      - APP_NAME=${APP_NAME:-Laravel WhatsApp}
      - APP_ENV=production
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=false
      - APP_URL=${APP_URL:-http://localhost}
      - LOG_CHANNEL=stack
      - LOG_LEVEL=error
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE:-laravel}
      - DB_USERNAME=${DB_USERNAME:-laravel}
      - DB_PASSWORD=${DB_PASSWORD}
      - CACHE_DRIVER=redis
      - FILESYSTEM_DISK=local
      - QUEUE_CONNECTION=redis
      - SESSION_DRIVER=redis
      - SESSION_LIFETIME=120
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      # WhatsApp específico (ajuste conforme seu projeto)
      - WHATSAPP_TOKEN=${WHATSAPP_TOKEN:-}
      - WHATSAPP_API_URL=${WHATSAPP_API_URL:-}
      - WHATSAPP_WEBHOOK_VERIFY=${WHATSAPP_WEBHOOK_VERIFY:-}
    volumes:
      - storage_data:/var/www/storage/app
      - logs_data:/var/www/storage/logs
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app_network
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  storage_data:
    driver: local
  logs_data:
    driver: local

networks:
  app_network:
    driver: bridge
